### ISSUE TITLE
invalid Syntax: cli.py : 82

### ISSUE THREAD

**Issue by CptanPanic** [yang/greminders2todoist#2]
* greminders2todoist version: Latest
* Python version: 3.5.2
* Operating System: Ubuntu Linux 16.04

### Description
I am not sure if this is due to using a newer version of linux and am not even familiar with this syntax, but my python does not like this : `frequency: Frequency`

**Comment by yang** [comment]
Ah, that's syntax introduced in 3.6 (see [this SO question for example](https://stackoverflow.com/questions/42002596/python-3-5-typed-namedtuple-syntax-produces-syntaxerror)).

You can can install a newer Python alongside your current one:

    sudo apt install python3.7

I like using virtualenvwrapper, so you can do something like this:

    sudo apt install virtualenvwrapper
    # log out and back in to your shell
    mkvirtualenv -p python3.7 greminders2todoist
    workon greminders2todoist
    cd /path/to/greminders2todoist
    pip install -e '.[test,dev]'
    greminders2todoist

Feel free to reopen if that doesn't work!
